-- ============================================================
-- QuickComm Master Consolidated Database Schema
-- Complete Single-File Setup for Fresh Databases
-- ============================================================

-- Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- 1. PROFILES TABLE (Extends Supabase auth.users)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id                    uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL PRIMARY KEY,
  role                  text CHECK (role IN ('admin', 'rider', 'user')) NOT NULL DEFAULT 'user',
  full_name             text,
  phone_number          text,
  must_change_password  boolean DEFAULT false,
  created_at            timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- 2. STORES TABLE (Multi-Store Foundation)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.stores (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL DEFAULT 'QuickComm Store',
  slug        text UNIQUE,
  owner_id    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  is_active   boolean DEFAULT true,
  created_at  timestamptz DEFAULT now() NOT NULL
);

INSERT INTO public.stores (id, name, slug)
VALUES (1, 'QuickComm Store', 'quickcomm-store')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- 3. BRANDS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.brands (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id    bigint REFERENCES public.stores(id) ON DELETE CASCADE DEFAULT 1,
  name        text NOT NULL,
  logo_url    text,
  is_active   boolean DEFAULT true,
  created_at  timestamptz DEFAULT now() NOT NULL,
  UNIQUE (store_id, name)
);

CREATE INDEX IF NOT EXISTS idx_brands_store ON public.brands(store_id);

-- ============================================================
-- 4. CATEGORIES TABLE (Hierarchical Tree)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.categories (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id    bigint REFERENCES public.stores(id) ON DELETE CASCADE DEFAULT 1,
  name        text NOT NULL,
  slug        text NOT NULL,
  parent_id   bigint REFERENCES public.categories(id) ON DELETE SET NULL,
  image_url   text,
  sort_order  int DEFAULT 0,
  is_active   boolean DEFAULT true,
  created_at  timestamptz DEFAULT now() NOT NULL,
  UNIQUE (store_id, slug)
);

CREATE INDEX IF NOT EXISTS idx_categories_parent ON public.categories(parent_id);
CREATE INDEX IF NOT EXISTS idx_categories_slug ON public.categories(store_id, slug);
CREATE INDEX IF NOT EXISTS idx_categories_store ON public.categories(store_id);

-- ============================================================
-- 5. PRODUCTS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.products (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id     bigint REFERENCES public.stores(id) ON DELETE CASCADE DEFAULT 1,
  name         text NOT NULL,
  slug         text,
  description  text,
  size         text,
  price        numeric DEFAULT 0,
  category     text NOT NULL DEFAULT 'Main Course',
  category_id  bigint REFERENCES public.categories(id) ON DELETE SET NULL,
  brand_id     bigint REFERENCES public.brands(id) ON DELETE SET NULL,
  image_url    text,
  images       text[] DEFAULT '{}',
  tags         text[] DEFAULT '{}',
  gst_rate     numeric DEFAULT 0,
  is_available boolean DEFAULT true,
  created_at   timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at   timestamptz DEFAULT now() NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_products_store_slug ON public.products(store_id, slug)
  WHERE slug IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_brand ON public.products(brand_id);
CREATE INDEX IF NOT EXISTS idx_products_store ON public.products(store_id);
CREATE INDEX IF NOT EXISTS idx_products_available ON public.products(is_available) WHERE is_available = true;

-- Full-text search index
CREATE INDEX IF NOT EXISTS idx_products_fts ON public.products
  USING gin(to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, '')));

-- ============================================================
-- 6. PRODUCT VARIANTS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.product_variants (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id        bigint REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
  sku               text,
  barcode           text,
  variant_name      text NOT NULL,
  unit_value        numeric,
  unit_type         text,
  mrp               numeric NOT NULL,
  selling_price     numeric NOT NULL,
  stock_quantity    int DEFAULT 0 CHECK (stock_quantity >= 0),
  low_stock_alert   int DEFAULT 10,
  is_available      boolean DEFAULT true,
  image_url         text,
  sort_order        int DEFAULT 0,
  created_at        timestamptz DEFAULT now() NOT NULL,
  updated_at        timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT selling_price_lte_mrp CHECK (selling_price <= mrp),
  UNIQUE (product_id, variant_name)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_variants_sku ON public.product_variants(sku) WHERE sku IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_variants_product ON public.product_variants(product_id);
CREATE INDEX IF NOT EXISTS idx_variants_available ON public.product_variants(is_available) WHERE is_available = true;

-- ============================================================
-- 7. ORDERS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.orders (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           uuid REFERENCES public.profiles(id) NOT NULL,
  rider_id          uuid REFERENCES public.profiles(id),
  status            text CHECK (status IN ('pending', 'confirmed', 'preparing', 'out_for_delivery', 'delivered', 'cancelled')) NOT NULL DEFAULT 'pending',
  total_amount      numeric NOT NULL,
  delivery_fee      numeric DEFAULT 0,
  discount_amount   numeric DEFAULT 0,
  coupon_code       text,
  payment_method    text CHECK (payment_method IN ('cod', 'upi', 'card', 'wallet', 'netbanking')) DEFAULT 'cod',
  payment_status    text CHECK (payment_status IN ('pending', 'paid', 'failed', 'refunded')) DEFAULT 'pending',
  delivery_address  text NOT NULL,
  delivery_lat      float,
  delivery_lng      float,
  delivery_notes    text,
  delivered_at      timestamptz,
  created_at        timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at        timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON public.orders(payment_status);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_rider_id ON public.orders(rider_id);

-- ============================================================
-- 8. ORDER ITEMS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.order_items (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id              bigint REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL,
  product_id            bigint REFERENCES public.products(id) NOT NULL,
  variant_id            bigint REFERENCES public.product_variants(id) ON DELETE SET NULL,
  product_name_snapshot text,
  variant_name_snapshot text,
  mrp_at_time           numeric,
  discount_at_time      numeric DEFAULT 0,
  quantity              int NOT NULL DEFAULT 1,
  price_at_time         numeric NOT NULL,
  created_at            timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_order_items_order ON public.order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product ON public.order_items(product_id);
CREATE INDEX IF NOT EXISTS idx_order_items_variant ON public.order_items(variant_id);

-- ============================================================
-- 9. CUSTOMERS & ADDRESSES
-- ============================================================
CREATE TABLE IF NOT EXISTS public.customers (
  id            uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL PRIMARY KEY,
  full_name     text,
  phone_number  text,
  address       text,
  created_at    timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.customer_addresses (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  label           text DEFAULT 'Home',
  address_line1   text NOT NULL,
  address_line2   text,
  landmark        text,
  city            text NOT NULL DEFAULT 'Hyderabad',
  pincode         text,
  lat             float,
  lng             float,
  is_default      boolean DEFAULT false,
  created_at      timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_customer_addresses_user ON public.customer_addresses(user_id);

-- ============================================================
-- 10. RIDER LOCATIONS & HISTORY & ATTENDANCE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.rider_locations (
  rider_id      uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL PRIMARY KEY,
  order_id      bigint REFERENCES public.orders(id) ON DELETE SET NULL,
  lat           float NOT NULL,
  lng           float NOT NULL,
  speed         float DEFAULT 0,
  heading       float DEFAULT 0,
  accuracy      float DEFAULT 0,
  last_updated  timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.rider_location_history (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rider_id      uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  order_id      bigint REFERENCES public.orders(id) ON DELETE SET NULL,
  lat           float NOT NULL,
  lng           float NOT NULL,
  speed         float DEFAULT 0,
  heading       float DEFAULT 0,
  accuracy      float DEFAULT 0,
  recorded_at   timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_rider_location_history_rider_time ON public.rider_location_history(rider_id, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_rider_location_history_order ON public.rider_location_history(order_id) WHERE order_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.rider_daily_stats (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rider_id        uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  date            date NOT NULL DEFAULT CURRENT_DATE,
  online_minutes  int NOT NULL DEFAULT 0,
  last_updated    timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT rider_daily_stats_rider_date_key UNIQUE (rider_id, date)
);

CREATE INDEX IF NOT EXISTS idx_rider_daily_stats_date ON public.rider_daily_stats(date);
CREATE INDEX IF NOT EXISTS idx_rider_daily_stats_rider ON public.rider_daily_stats(rider_id);

-- ============================================================
-- 11. STORE SETTINGS (Global Configuration)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.store_settings (
  id                  int PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  lat                 float NOT NULL DEFAULT 17.3850,
  lng                 float NOT NULL DEFAULT 78.4867,
  store_name          text DEFAULT 'QuickComm Store',
  store_logo_url      text,
  store_address       text DEFAULT 'Hyderabad, Telangana',
  phone_number        text,
  delivery_radius_km  numeric DEFAULT 5,
  min_order_amount    numeric DEFAULT 99,
  delivery_fee_fixed  numeric DEFAULT 20,
  free_delivery_above numeric DEFAULT 299,
  is_open             boolean DEFAULT true,
  opening_time        time DEFAULT '09:00',
  closing_time        time DEFAULT '23:00',
  days_open           text[] DEFAULT '{Mon,Tue,Wed,Thu,Fri,Sat,Sun}',
  updated_at          timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed Default Store Settings Row
INSERT INTO public.store_settings (
  id, lat, lng, store_name, store_address, delivery_radius_km, min_order_amount,
  delivery_fee_fixed, free_delivery_above, is_open, opening_time, closing_time,
  days_open, updated_at
) VALUES (
  1, 17.3850, 78.4867, 'QuickComm Store', 'Hyderabad, Telangana', 5.0, 99.0,
  20.0, 299.0, true, '09:00', '23:00',
  ARRAY['Mon','Tue','Wed','Thu','Fri','Sat','Sun'], now()
)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- 12. TRIGGERS & FUNCTIONS
-- ============================================================

-- Function: Handle New User Signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role)
  VALUES (NEW.id, NEW.raw_user_meta_data->>'full_name', 'user')
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Function: Audit Rider Location History
CREATE OR REPLACE FUNCTION public.log_rider_location_history()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.rider_location_history (
    rider_id, order_id, lat, lng, speed, heading, accuracy, recorded_at
  ) VALUES (
    NEW.rider_id, NEW.order_id, NEW.lat, NEW.lng,
    COALESCE(NEW.speed, 0), COALESCE(NEW.heading, 0), COALESCE(NEW.accuracy, 0),
    COALESCE(NEW.last_updated, now())
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_rider_location_upsert ON public.rider_locations;
CREATE TRIGGER on_rider_location_upsert
  AFTER INSERT OR UPDATE ON public.rider_locations
  FOR EACH ROW EXECUTE FUNCTION public.log_rider_location_history();

-- Function: Auto Set updated_at
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS products_set_updated_at ON public.products;
CREATE TRIGGER products_set_updated_at
  BEFORE UPDATE ON public.products
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS variants_set_updated_at ON public.product_variants;
CREATE TRIGGER variants_set_updated_at
  BEFORE UPDATE ON public.product_variants
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Function: Enforce Single Default Address
CREATE OR REPLACE FUNCTION public.enforce_single_default_address()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.is_default = true THEN
    UPDATE public.customer_addresses
    SET is_default = false
    WHERE user_id = NEW.user_id AND id != NEW.id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_address_default_set ON public.customer_addresses;
CREATE TRIGGER on_address_default_set
  AFTER INSERT OR UPDATE OF is_default ON public.customer_addresses
  FOR EACH ROW
  WHEN (NEW.is_default = true)
  EXECUTE FUNCTION public.enforce_single_default_address();

-- Function: Decrement Variant Stock Safely
CREATE OR REPLACE FUNCTION public.decrement_variant_stock(p_variant_id bigint, p_quantity int)
RETURNS void AS $$
BEGIN
  UPDATE public.product_variants
  SET stock_quantity = GREATEST(0, stock_quantity - p_quantity),
      updated_at = now()
  WHERE id = p_variant_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function: Restore Variant Stock
CREATE OR REPLACE FUNCTION public.increment_variant_stock(p_variant_id bigint, p_quantity int)
RETURNS void AS $$
BEGIN
  UPDATE public.product_variants
  SET stock_quantity = stock_quantity + p_quantity,
      updated_at = now()
  WHERE id = p_variant_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- 13. ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rider_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rider_location_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rider_daily_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;

-- Profiles
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Stores & Brands & Categories
DROP POLICY IF EXISTS "stores_read_all" ON public.stores;
CREATE POLICY "stores_read_all" ON public.stores FOR SELECT USING (true);
DROP POLICY IF EXISTS "brands_read_all" ON public.brands;
CREATE POLICY "brands_read_all" ON public.brands FOR SELECT USING (true);
DROP POLICY IF EXISTS "categories_read_all" ON public.categories;
CREATE POLICY "categories_read_all" ON public.categories FOR SELECT USING (true);

-- Products & Variants (Public Read, Admin Write)
DROP POLICY IF EXISTS "products_read_all" ON public.products;
CREATE POLICY "products_read_all" ON public.products FOR SELECT USING (true);
DROP POLICY IF EXISTS "variants_read_all" ON public.product_variants;
CREATE POLICY "variants_read_all" ON public.product_variants FOR SELECT USING (true);

DROP POLICY IF EXISTS "products_admin_write" ON public.products;
CREATE POLICY "products_admin_write" ON public.products FOR ALL
  USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "variants_admin_write" ON public.product_variants;
CREATE POLICY "variants_admin_write" ON public.product_variants FOR ALL
  USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- Orders
DROP POLICY IF EXISTS "orders_select_policy" ON public.orders;
CREATE POLICY "orders_select_policy" ON public.orders FOR SELECT USING (
  auth.uid() = user_id OR
  EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('admin', 'rider'))
);

DROP POLICY IF EXISTS "orders_insert_policy" ON public.orders;
CREATE POLICY "orders_insert_policy" ON public.orders FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "orders_update_policy" ON public.orders;
CREATE POLICY "orders_update_policy" ON public.orders FOR UPDATE USING (true);

-- Order Items
DROP POLICY IF EXISTS "order_items_select_policy" ON public.order_items;
CREATE POLICY "order_items_select_policy" ON public.order_items FOR SELECT USING (
  order_id IN (
    SELECT id FROM public.orders
    WHERE user_id = auth.uid() OR EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('admin', 'rider'))
  )
);

DROP POLICY IF EXISTS "order_items_insert_policy" ON public.order_items;
CREATE POLICY "order_items_insert_policy" ON public.order_items FOR INSERT WITH CHECK (
  order_id IN (SELECT id FROM public.orders WHERE user_id = auth.uid())
);

-- Rider Locations & History
DROP POLICY IF EXISTS "rider_locations_select" ON public.rider_locations;
CREATE POLICY "rider_locations_select" ON public.rider_locations FOR SELECT USING (true);
DROP POLICY IF EXISTS "rider_locations_insert" ON public.rider_locations;
CREATE POLICY "rider_locations_insert" ON public.rider_locations FOR INSERT WITH CHECK (auth.uid() = rider_id);
DROP POLICY IF EXISTS "rider_locations_update" ON public.rider_locations;
CREATE POLICY "rider_locations_update" ON public.rider_locations FOR UPDATE USING (auth.uid() = rider_id);

DROP POLICY IF EXISTS "rider_location_history_select" ON public.rider_location_history;
CREATE POLICY "rider_location_history_select" ON public.rider_location_history FOR SELECT USING (true);

-- Rider Daily Stats
DROP POLICY IF EXISTS "rider_daily_stats_read" ON public.rider_daily_stats;
CREATE POLICY "rider_daily_stats_read" ON public.rider_daily_stats FOR SELECT USING (true);
DROP POLICY IF EXISTS "rider_daily_stats_insert" ON public.rider_daily_stats;
CREATE POLICY "rider_daily_stats_insert" ON public.rider_daily_stats FOR INSERT WITH CHECK (auth.uid() = rider_id);
DROP POLICY IF EXISTS "rider_daily_stats_update" ON public.rider_daily_stats;
CREATE POLICY "rider_daily_stats_update" ON public.rider_daily_stats FOR UPDATE USING (auth.uid() = rider_id);

-- Customer Addresses
DROP POLICY IF EXISTS "addresses_select_own" ON public.customer_addresses;
CREATE POLICY "addresses_select_own" ON public.customer_addresses FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "addresses_insert_own" ON public.customer_addresses;
CREATE POLICY "addresses_insert_own" ON public.customer_addresses FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "addresses_update_own" ON public.customer_addresses;
CREATE POLICY "addresses_update_own" ON public.customer_addresses FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "addresses_delete_own" ON public.customer_addresses;
CREATE POLICY "addresses_delete_own" ON public.customer_addresses FOR DELETE USING (auth.uid() = user_id);

-- Store Settings
DROP POLICY IF EXISTS "store_settings_read" ON public.store_settings;
CREATE POLICY "store_settings_read" ON public.store_settings FOR SELECT USING (true);
DROP POLICY IF EXISTS "store_settings_admin_write" ON public.store_settings;
CREATE POLICY "store_settings_admin_write" ON public.store_settings FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- ============================================================
-- 14. REALTIME PUBLICATION
-- ============================================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;
END $$;

ALTER PUBLICATION supabase_realtime ADD TABLE public.rider_locations;
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
ALTER PUBLICATION supabase_realtime ADD TABLE public.profiles;
ALTER PUBLICATION supabase_realtime ADD TABLE public.rider_daily_stats;
ALTER PUBLICATION supabase_realtime ADD TABLE public.store_settings;

-- ============================================================
-- 15. STORAGE BUCKETS & POLICIES
-- ============================================================
INSERT INTO storage.buckets (id, name, public)
VALUES 
  ('product-images', 'product-images', true),
  ('category-images', 'category-images', true),
  ('brand-logos', 'brand-logos', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Public view store images" ON storage.objects;
CREATE POLICY "Public view store images" ON storage.objects
  FOR SELECT USING (bucket_id IN ('product-images', 'category-images', 'brand-logos'));

DROP POLICY IF EXISTS "Admin upload store images" ON storage.objects;
CREATE POLICY "Admin upload store images" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id IN ('product-images', 'category-images', 'brand-logos')
  );

DROP POLICY IF EXISTS "Admin delete store images" ON storage.objects;
CREATE POLICY "Admin delete store images" ON storage.objects
  FOR DELETE USING (
    bucket_id IN ('product-images', 'category-images', 'brand-logos')
  );

