-- Enable PostGIS if needed for advanced geo-queries, but we'll stick to simple lat/lng first
-- create extension if not exists postgis;

-- Profiles table (extends auth.users)
create table public.profiles (
  id uuid references auth.users not null primary key,
  role text check (role in ('admin', 'rider', 'user')) not null default 'user',
  full_name text,
  phone_number text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Products table
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  size text, -- e.g., 'Single', 'Family', 'Jumbo'
  price numeric not null,
  category text not null default 'Main Course', -- e.g., 'Biryani', 'Starters'
  image_url text, -- For product images
  is_available boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Orders table
create table public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  rider_id uuid references public.profiles(id), -- Assigned rider
  status text check (status in ('pending', 'confirmed', 'preparing', 'out_for_delivery', 'delivered', 'cancelled')) not null default 'pending',
  total_amount numeric not null,
  delivery_address text not null,
  delivery_lat float,
  delivery_lng float,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Order Items (to link orders and products)
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) not null,
  product_id bigint references public.products(id) not null,
  quantity int not null default 1,
  price_at_time numeric not null, -- Store price at time of order
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Rider Locations (for Realtime tracking)
create table public.rider_locations (
  id bigint generated by default as identity primary key,
  rider_id uuid references public.profiles(id) not null,
  lat float not null,
  lng float not null,
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Realtime for rider_locations
alter publication supabase_realtime add table public.rider_locations;
alter publication supabase_realtime add table public.orders; -- Useful for admin panel updates

-- RLS Policies (Basic examples, refine geared towards security later)
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.rider_locations enable row level security;
alter table public.order_items enable row level security;

-- Profiles: Users can read their own profile, Admins can read all
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- Products: Readable by all, Insert/Update by Admin only
create policy "Products are viewable by everyone" on products for select using (true);

-- Orders: Users see own, Riders see assigned or available (if needed), Admins see all
create policy "Users can see own orders" on orders for select using (auth.uid() = user_id);
-- (Add policies for riders/admins later based on role check functions)

-- Rider Locations: Public read (for demo simplicity) or restricted to active orders
create policy "Locations viewable by all" on rider_locations for select using (true);
create policy "Riders update own location" on rider_locations for insert with check (auth.uid() = rider_id);
create policy "Riders update own location update" on rider_locations for update using (auth.uid() = rider_id);

-- Trigger to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data->>'full_name', 'user');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users

-- Customers table (for End Users)
create table public.customers (
  id uuid references auth.users not null primary key,
  full_name text,
  phone_number text,
  address text, -- Default delivery address
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Customers
alter table public.customers enable row level security;
create policy "Customers can view their own profile" on customers for select using (auth.uid() = id);
create policy "Customers can insert their own profile" on customers for insert with check (auth.uid() = id);
create policy "Customers can update their own profile" on customers for update using (auth.uid() = id);

-- Fix Orders RLS
-- Allow users to insert orders
create policy "Users can insert their own orders" on orders for insert with check (auth.uid() = user_id);
-- Fix Order Items RLS
create policy "Users can insert own order items" on order_items 
  for insert with check (
    order_id in (select id from orders where user_id = auth.uid())
  );

create policy "Users can view own order items" on order_items
  for select using (
    order_id in (select id from orders where user_id = auth.uid())
  );

