-- Enable PostGIS if needed for advanced geo-queries, but we'll stick to simple lat/lng first
-- create extension if not exists postgis;

-- Profiles table (extends auth.users)
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  role text check (role in ('admin', 'rider', 'user')) not null default 'user',
  full_name text,
  phone_number text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Products table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  size text, -- e.g., 'Single', 'Family', 'Jumbo'
  price numeric not null,
  category text not null default 'Main Course', -- e.g., 'Biryani', 'Starters'
  image_url text, -- For product images
  is_available boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Orders table
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  rider_id uuid references public.profiles(id), -- Assigned rider
  status text check (status in ('pending', 'confirmed', 'preparing', 'out_for_delivery', 'delivered', 'cancelled')) not null default 'pending',
  total_amount numeric not null,
  delivery_address text not null,
  delivery_lat float,
  delivery_lng float,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Order Items (to link orders and products)
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) not null,
  product_id bigint references public.products(id) not null,
  quantity int not null default 1,
  price_at_time numeric not null, -- Store price at time of order
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Rider Locations (for Realtime tracking)
create table if not exists public.rider_locations (
  rider_id uuid references auth.users not null primary key,
  order_id bigint references public.orders(id), -- Nullable, tracks active order
  lat float not null,
  lng float not null,
  speed float default 0, -- m/s from device GPS
  heading float default 0, -- degrees (0-360) from device compass
  accuracy float default 0, -- horizontal accuracy in meters
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Rider Location History (audit trail for disputes and analytics)
create table if not exists public.rider_location_history (
  id bigint generated by default as identity primary key,
  rider_id uuid references auth.users not null,
  order_id bigint references public.orders(id),
  lat float not null,
  lng float not null,
  speed float default 0,
  heading float default 0,
  accuracy float default 0,
  recorded_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Customers table (for End Users)
create table if not exists public.customers (
  id uuid references auth.users not null primary key,
  full_name text,
  phone_number text,
  address text, -- Default delivery address
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Store Settings (Global configuration)
create table if not exists public.store_settings (
  id int primary key default 1 check (id = 1), -- Ensure only one row exists
  lat float not null,
  lng float not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Realtime for relevant tables
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table public.rider_locations;
alter publication supabase_realtime add table public.orders;
alter publication supabase_realtime add table public.profiles;

-- RLS Policies Enable
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.rider_locations enable row level security;
alter table public.order_items enable row level security;
alter table public.customers enable row level security;
alter table public.store_settings enable row level security;

-- Profiles Policies
drop policy if exists "Public profiles are viewable by everyone" on profiles;
create policy "Public profiles are viewable by everyone" on profiles for select using (true);

drop policy if exists "Users can insert their own profile" on profiles;
create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);

drop policy if exists "Users can update own profile" on profiles;
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- Products Policies
drop policy if exists "Products are viewable by everyone" on products;
create policy "Products are viewable by everyone" on products for select using (true);

drop policy if exists "Enable read access for all users" on products;
create policy "Enable read access for all users" on products for select using (true);

-- Orders Policies
drop policy if exists "Users can see own orders" on orders;
create policy "Users can see own orders" on orders for select using (auth.uid() = user_id);

drop policy if exists "Users can insert their own orders" on orders;
create policy "Users can insert their own orders" on orders for insert with check (auth.uid() = user_id);

drop policy if exists "Enable update for all users" on orders;
create policy "Enable update for all users" on orders for update using (true);

-- Order Items Policies
drop policy if exists "Users can insert own order items" on order_items;
create policy "Users can insert own order items" on order_items 
  for insert with check (
    order_id in (select id from orders where user_id = auth.uid())
  );

drop policy if exists "Users can view own order items" on order_items;
create policy "Users can view own order items" on order_items
  for select using (
    order_id in (select id from orders where user_id = auth.uid())
  );

-- Rider Locations Policies
drop policy if exists "Locations viewable by all" on rider_locations;
create policy "Locations viewable by all" on rider_locations for select using (true);

drop policy if exists "Riders insert own location" on rider_locations;
create policy "Riders insert own location" on rider_locations for insert with check (auth.uid() = rider_id);

drop policy if exists "Riders update own location" on rider_locations;
create policy "Riders update own location" on rider_locations for update using (auth.uid() = rider_id);

drop policy if exists "Riders update own location update" on rider_locations; -- Cleanup old policy name

-- Customers Policies
drop policy if exists "Customers can view their own profile" on customers;
create policy "Customers can view their own profile" on customers for select using (auth.uid() = id);

drop policy if exists "Customers can insert their own profile" on customers;
create policy "Customers can insert their own profile" on customers for insert with check (auth.uid() = id);

drop policy if exists "Customers can update their own profile" on customers;
create policy "Customers can update their own profile" on customers for update using (auth.uid() = id);

-- Store Settings Policies
drop policy if exists "Store settings are viewable by everyone" on store_settings;
create policy "Store settings are viewable by everyone" on store_settings for select using (true);

drop policy if exists "Admins can update store settings" on store_settings;
create policy "Admins can update store settings" on store_settings for update using (
  exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role = 'admin')
);

drop policy if exists "Admins can insert store settings" on store_settings;
create policy "Admins can insert store settings" on store_settings for insert with check (
  exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role = 'admin')
);

-- Insert a default store location (e.g., somewhere in Hyderabad)
insert into public.store_settings (id, lat, lng) values (1, 17.3850, 78.4867) on conflict (id) do nothing;

-- Trigger to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data->>'full_name', 'user');
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
