-- P2 Migration: Location history, auto-logging trigger, and stale cleanup
-- Run this on your Supabase SQL Editor

-- ============================================================
-- 1. RIDER LOCATION HISTORY TABLE (Audit Trail)
-- ============================================================
-- Stores every location update for dispute resolution and analytics.
-- The trigger below auto-populates this on every rider_locations upsert.

CREATE TABLE IF NOT EXISTS public.rider_location_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rider_id uuid REFERENCES auth.users NOT NULL,
  order_id bigint REFERENCES public.orders(id),
  lat float NOT NULL,
  lng float NOT NULL,
  speed float DEFAULT 0,
  heading float DEFAULT 0,
  accuracy float DEFAULT 0,
  recorded_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for fast lookups by rider + time range (e.g. "show me rider X's path today")
CREATE INDEX IF NOT EXISTS idx_rider_location_history_rider_time 
  ON public.rider_location_history (rider_id, recorded_at DESC);

-- Index for order-specific path (e.g. "show me the path for order #123")
CREATE INDEX IF NOT EXISTS idx_rider_location_history_order 
  ON public.rider_location_history (order_id) WHERE order_id IS NOT NULL;

-- RLS: riders can see their own history, admins can see all
ALTER TABLE public.rider_location_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Location history viewable by all" ON rider_location_history;
CREATE POLICY "Location history viewable by all" ON rider_location_history 
  FOR SELECT USING (true);

-- No INSERT/UPDATE/DELETE policies for users — only the trigger writes to this table


-- ============================================================
-- 2. AUTO-INSERT TRIGGER (Logs every location update to history)
-- ============================================================
-- Fires on every INSERT or UPDATE to rider_locations and copies
-- the new row into rider_location_history. Zero app code changes needed.

CREATE OR REPLACE FUNCTION public.log_rider_location_history()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.rider_location_history (
    rider_id, order_id, lat, lng, speed, heading, accuracy, recorded_at
  ) VALUES (
    NEW.rider_id, NEW.order_id, NEW.lat, NEW.lng, 
    COALESCE(NEW.speed, 0), COALESCE(NEW.heading, 0), COALESCE(NEW.accuracy, 0),
    COALESCE(NEW.last_updated, now())
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_rider_location_upsert ON public.rider_locations;
CREATE TRIGGER on_rider_location_upsert
  AFTER INSERT OR UPDATE ON public.rider_locations
  FOR EACH ROW
  EXECUTE FUNCTION public.log_rider_location_history();


-- ============================================================
-- 3. STALE RIDER CLEANUP FUNCTION
-- ============================================================
-- Deletes rider_locations rows where last_updated is older than 24 hours.
-- Prevents phantom riders from appearing on the admin map.
-- 
-- Call manually: SELECT public.cleanup_stale_rider_locations();
-- Or set up a Supabase cron job (pg_cron) to run it daily:
--   SELECT cron.schedule('cleanup-stale-riders', '0 3 * * *', 'SELECT public.cleanup_stale_rider_locations()');

CREATE OR REPLACE FUNCTION public.cleanup_stale_rider_locations()
RETURNS integer AS $$
DECLARE
  deleted_count integer;
BEGIN
  DELETE FROM public.rider_locations
  WHERE last_updated < now() - interval '24 hours';
  
  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  RETURN deleted_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- ============================================================
-- 4. HISTORY CLEANUP (Optional — prevent unbounded growth)
-- ============================================================
-- Deletes history records older than 30 days.
-- Call via cron: SELECT cron.schedule('cleanup-location-history', '0 4 * * 0', 'SELECT public.cleanup_old_location_history()');

CREATE OR REPLACE FUNCTION public.cleanup_old_location_history()
RETURNS integer AS $$
DECLARE
  deleted_count integer;
BEGIN
  DELETE FROM public.rider_location_history
  WHERE recorded_at < now() - interval '30 days';
  
  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  RETURN deleted_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
