-- ============================================================
-- P3 Migration: Supermarket Product Catalog
-- Run this in Supabase SQL Editor AFTER existing schema is applied
-- This is ADDITIVE — no existing data is dropped
-- ============================================================

-- ============================================================
-- 0. STORES TABLE (Multi-store foundation)
-- ============================================================
-- Enables future franchise/multi-store support.
-- For now, one default store (id=1) owns everything.

CREATE TABLE IF NOT EXISTS public.stores (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL DEFAULT 'QuickComm Store',
  slug        text UNIQUE,
  owner_id    uuid REFERENCES auth.users ON DELETE SET NULL,
  is_active   boolean DEFAULT true,
  created_at  timestamptz DEFAULT now() NOT NULL
);

-- Seed the default store
INSERT INTO public.stores (id, name, slug)
VALUES (1, 'QuickComm Store', 'quickcomm-store')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "stores_read_all" ON public.stores;
CREATE POLICY "stores_read_all" ON public.stores FOR SELECT USING (true);

DROP POLICY IF EXISTS "stores_admin_write" ON public.stores;
CREATE POLICY "stores_admin_write" ON public.stores FOR ALL
  USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));


-- ============================================================
-- 1. BRANDS TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS public.brands (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id    bigint REFERENCES public.stores(id) ON DELETE CASCADE DEFAULT 1,
  name        text NOT NULL,
  logo_url    text,
  is_active   boolean DEFAULT true,
  created_at  timestamptz DEFAULT now() NOT NULL,
  UNIQUE (store_id, name)
);

CREATE INDEX IF NOT EXISTS idx_brands_store ON public.brands(store_id);

ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "brands_read_all" ON public.brands;
CREATE POLICY "brands_read_all" ON public.brands FOR SELECT USING (true);

DROP POLICY IF EXISTS "brands_admin_insert" ON public.brands;
CREATE POLICY "brands_admin_insert" ON public.brands FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "brands_admin_update" ON public.brands;
CREATE POLICY "brands_admin_update" ON public.brands FOR UPDATE
  USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "brands_admin_delete" ON public.brands;
CREATE POLICY "brands_admin_delete" ON public.brands FOR DELETE
  USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- Seed common Indian grocery brands
INSERT INTO public.brands (store_id, name) VALUES
  (1, 'Amul'),
  (1, 'Mother Dairy'),
  (1, 'Britannia'),
  (1, 'Parle'),
  (1, 'Haldiram''s'),
  (1, 'Nestle'),
  (1, 'ITC'),
  (1, 'Dabur'),
  (1, 'Patanjali'),
  (1, 'Tata'),
  (1, 'Marico'),
  (1, 'HUL'),
  (1, 'P&G'),
  (1, 'Godrej'),
  (1, 'Aashirvaad'),
  (1, 'Fortune'),
  (1, 'Saffola'),
  (1, 'Tropicana'),
  (1, 'Real'),
  (1, 'Paper Boat')
ON CONFLICT DO NOTHING;


-- ============================================================
-- 2. CATEGORIES TABLE (Self-referencing tree)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.categories (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id    bigint REFERENCES public.stores(id) ON DELETE CASCADE DEFAULT 1,
  name        text NOT NULL,
  slug        text NOT NULL,
  parent_id   bigint REFERENCES public.categories(id) ON DELETE SET NULL,
  image_url   text,
  sort_order  int DEFAULT 0,
  is_active   boolean DEFAULT true,
  created_at  timestamptz DEFAULT now() NOT NULL,
  UNIQUE (store_id, slug)
);

CREATE INDEX IF NOT EXISTS idx_categories_parent ON public.categories(parent_id);
CREATE INDEX IF NOT EXISTS idx_categories_slug ON public.categories(store_id, slug);
CREATE INDEX IF NOT EXISTS idx_categories_store ON public.categories(store_id);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "categories_read_all" ON public.categories;
CREATE POLICY "categories_read_all" ON public.categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "categories_admin_insert" ON public.categories;
CREATE POLICY "categories_admin_insert" ON public.categories FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "categories_admin_update" ON public.categories;
CREATE POLICY "categories_admin_update" ON public.categories FOR UPDATE
  USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "categories_admin_delete" ON public.categories;
CREATE POLICY "categories_admin_delete" ON public.categories FOR DELETE
  USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- -----------------------------------------------
-- Seed: Supermarket Category Tree
-- -----------------------------------------------
-- Top-level categories (parent_id = NULL)
INSERT INTO public.categories (store_id, name, slug, parent_id, sort_order) VALUES
  (1, 'Fruits & Vegetables',       'fruits-vegetables',      NULL, 1),
  (1, 'Dairy, Bread & Eggs',       'dairy-bread-eggs',       NULL, 2),
  (1, 'Beverages',                  'beverages',              NULL, 3),
  (1, 'Snacks & Munchies',          'snacks-munchies',        NULL, 4),
  (1, 'Breakfast & Instant Food',   'breakfast-instant-food', NULL, 5),
  (1, 'Staples & Cooking',          'staples-cooking',        NULL, 6),
  (1, 'Meat, Fish & Eggs',          'meat-fish-eggs',         NULL, 7),
  (1, 'Personal Care',              'personal-care',          NULL, 8),
  (1, 'Home & Kitchen',             'home-kitchen',           NULL, 9),
  (1, 'Baby Care',                  'baby-care',              NULL, 10),
  (1, 'Uncategorized',              'uncategorized',          NULL, 99)
ON CONFLICT DO NOTHING;

-- Sub-categories: Fruits & Vegetables
INSERT INTO public.categories (store_id, name, slug, parent_id, sort_order)
SELECT 1, sub.name, sub.slug, c.id, sub.sort_order
FROM (VALUES
  ('Fresh Fruits',         'fresh-fruits',          1),
  ('Fresh Vegetables',     'fresh-vegetables',      2),
  ('Herbs & Seasonings',   'herbs-seasonings',      3),
  ('Exotic Fruits & Vegs', 'exotic-fruits-vegs',    4)
) AS sub(name, slug, sort_order)
CROSS JOIN (SELECT id FROM public.categories WHERE slug = 'fruits-vegetables' LIMIT 1) c
ON CONFLICT DO NOTHING;

-- Sub-categories: Dairy, Bread & Eggs
INSERT INTO public.categories (store_id, name, slug, parent_id, sort_order)
SELECT 1, sub.name, sub.slug, c.id, sub.sort_order
FROM (VALUES
  ('Milk',                'milk',               1),
  ('Curd & Yoghurt',      'curd-yoghurt',       2),
  ('Cheese & Butter',     'cheese-butter',      3),
  ('Bread & Bakery',      'bread-bakery',       4),
  ('Eggs',                'eggs',               5),
  ('Paneer & Tofu',       'paneer-tofu',        6)
) AS sub(name, slug, sort_order)
CROSS JOIN (SELECT id FROM public.categories WHERE slug = 'dairy-bread-eggs' LIMIT 1) c
ON CONFLICT DO NOTHING;

-- Sub-categories: Beverages
INSERT INTO public.categories (store_id, name, slug, parent_id, sort_order)
SELECT 1, sub.name, sub.slug, c.id, sub.sort_order
FROM (VALUES
  ('Cold Drinks',         'cold-drinks',        1),
  ('Juices',              'juices',             2),
  ('Tea & Coffee',        'tea-coffee',         3),
  ('Health Drinks',       'health-drinks',      4),
  ('Water & Soda',        'water-soda',         5),
  ('Energy Drinks',       'energy-drinks',      6)
) AS sub(name, slug, sort_order)
CROSS JOIN (SELECT id FROM public.categories WHERE slug = 'beverages' LIMIT 1) c
ON CONFLICT DO NOTHING;

-- Sub-categories: Snacks & Munchies
INSERT INTO public.categories (store_id, name, slug, parent_id, sort_order)
SELECT 1, sub.name, sub.slug, c.id, sub.sort_order
FROM (VALUES
  ('Chips & Namkeen',     'chips-namkeen',      1),
  ('Biscuits & Cookies',  'biscuits-cookies',   2),
  ('Chocolates & Candy',  'chocolates-candy',   3),
  ('Dry Fruits & Nuts',   'dry-fruits-nuts',    4),
  ('Sweets & Mithai',     'sweets-mithai',      5)
) AS sub(name, slug, sort_order)
CROSS JOIN (SELECT id FROM public.categories WHERE slug = 'snacks-munchies' LIMIT 1) c
ON CONFLICT DO NOTHING;

-- Sub-categories: Staples & Cooking
INSERT INTO public.categories (store_id, name, slug, parent_id, sort_order)
SELECT 1, sub.name, sub.slug, c.id, sub.sort_order
FROM (VALUES
  ('Atta & Flour',        'atta-flour',         1),
  ('Rice',                'rice',               2),
  ('Dal & Pulses',        'dal-pulses',         3),
  ('Oils & Ghee',         'oils-ghee',          4),
  ('Spices & Masala',     'spices-masala',      5),
  ('Sugar, Salt & Jaggery','sugar-salt-jaggery',6),
  ('Sauces & Condiments', 'sauces-condiments',  7)
) AS sub(name, slug, sort_order)
CROSS JOIN (SELECT id FROM public.categories WHERE slug = 'staples-cooking' LIMIT 1) c
ON CONFLICT DO NOTHING;

-- Sub-categories: Personal Care
INSERT INTO public.categories (store_id, name, slug, parent_id, sort_order)
SELECT 1, sub.name, sub.slug, c.id, sub.sort_order
FROM (VALUES
  ('Skin Care',           'skin-care',          1),
  ('Hair Care',           'hair-care',          2),
  ('Oral Care',           'oral-care',          3),
  ('Bath & Body',         'bath-body',          4),
  ('Feminine Hygiene',    'feminine-hygiene',   5)
) AS sub(name, slug, sort_order)
CROSS JOIN (SELECT id FROM public.categories WHERE slug = 'personal-care' LIMIT 1) c
ON CONFLICT DO NOTHING;

-- Sub-categories: Home & Kitchen
INSERT INTO public.categories (store_id, name, slug, parent_id, sort_order)
SELECT 1, sub.name, sub.slug, c.id, sub.sort_order
FROM (VALUES
  ('Cleaning Supplies',   'cleaning-supplies',  1),
  ('Detergents & Fabric', 'detergents-fabric',  2),
  ('Kitchen Tools',       'kitchen-tools',      3),
  ('Fresheners & Repellents','fresheners-repellents',4)
) AS sub(name, slug, sort_order)
CROSS JOIN (SELECT id FROM public.categories WHERE slug = 'home-kitchen' LIMIT 1) c
ON CONFLICT DO NOTHING;


-- ============================================================
-- 3. ALTER PRODUCTS TABLE (Additive — no drops)
-- ============================================================

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS store_id    bigint REFERENCES public.stores(id) ON DELETE CASCADE DEFAULT 1,
  ADD COLUMN IF NOT EXISTS slug        text,
  ADD COLUMN IF NOT EXISTS brand_id    bigint REFERENCES public.brands(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS category_id bigint REFERENCES public.categories(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS tags        text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS images      text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS gst_rate    numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS updated_at  timestamptz DEFAULT now(),
  ALTER COLUMN price DROP NOT NULL,
  ALTER COLUMN price SET DEFAULT 0;

-- Unique slug per store
CREATE UNIQUE INDEX IF NOT EXISTS idx_products_store_slug ON public.products(store_id, slug)
  WHERE slug IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_brand ON public.products(brand_id);
CREATE INDEX IF NOT EXISTS idx_products_store ON public.products(store_id);
CREATE INDEX IF NOT EXISTS idx_products_available ON public.products(is_available) WHERE is_available = true;

-- Full-text search index on product name + description
CREATE INDEX IF NOT EXISTS idx_products_fts ON public.products
  USING gin(to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, '')));

-- Migrate existing products: assign to "Uncategorized"
UPDATE public.products
SET category_id = (SELECT id FROM public.categories WHERE slug = 'uncategorized' LIMIT 1),
    store_id = 1
WHERE category_id IS NULL;

-- Add admin write policies (read is already open from original schema)
DROP POLICY IF EXISTS "products_admin_insert" ON public.products;
CREATE POLICY "products_admin_insert" ON public.products FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "products_admin_update" ON public.products;
CREATE POLICY "products_admin_update" ON public.products FOR UPDATE
  USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "products_admin_delete" ON public.products;
CREATE POLICY "products_admin_delete" ON public.products FOR DELETE
  USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));


-- ============================================================
-- 4. PRODUCT VARIANTS TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS public.product_variants (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id        bigint REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,

  -- Identity
  sku               text,
  barcode           text,

  -- What makes this variant unique
  variant_name      text NOT NULL,          -- "500 ml", "1 kg", "Pack of 6"
  unit_value        numeric,                -- 500, 1, 6
  unit_type         text,                   -- 'ml'|'l'|'g'|'kg'|'pcs'|'pack'

  -- Pricing
  mrp               numeric NOT NULL,
  selling_price     numeric NOT NULL,

  -- Inventory
  stock_quantity    int DEFAULT 0 CHECK (stock_quantity >= 0),
  low_stock_alert   int DEFAULT 10,
  is_available      boolean DEFAULT true,

  -- Display
  image_url         text,
  sort_order        int DEFAULT 0,

  created_at        timestamptz DEFAULT now() NOT NULL,
  updated_at        timestamptz DEFAULT now() NOT NULL,

  -- Constraints
  CONSTRAINT selling_price_lte_mrp CHECK (selling_price <= mrp),
  UNIQUE (product_id, variant_name)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_variants_sku ON public.product_variants(sku)
  WHERE sku IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_variants_product ON public.product_variants(product_id);
CREATE INDEX IF NOT EXISTS idx_variants_available ON public.product_variants(is_available)
  WHERE is_available = true;
CREATE INDEX IF NOT EXISTS idx_variants_barcode ON public.product_variants(barcode)
  WHERE barcode IS NOT NULL;

ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "variants_read_all" ON public.product_variants;
CREATE POLICY "variants_read_all" ON public.product_variants FOR SELECT USING (true);

DROP POLICY IF EXISTS "variants_admin_insert" ON public.product_variants;
CREATE POLICY "variants_admin_insert" ON public.product_variants FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "variants_admin_update" ON public.product_variants;
CREATE POLICY "variants_admin_update" ON public.product_variants FOR UPDATE
  USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "variants_admin_delete" ON public.product_variants;
CREATE POLICY "variants_admin_delete" ON public.product_variants FOR DELETE
  USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- Migrate existing products: create a default variant for each
-- Uses the old price/size fields as the source of truth
INSERT INTO public.product_variants (
  product_id, variant_name, mrp, selling_price, stock_quantity, is_available, sort_order
)
SELECT
  id,
  COALESCE(NULLIF(TRIM(size), ''), 'Standard') AS variant_name,
  price         AS mrp,
  price         AS selling_price,
  999           AS stock_quantity,   -- generous default for existing items
  is_available,
  0             AS sort_order
FROM public.products
WHERE id NOT IN (SELECT DISTINCT product_id FROM public.product_variants)
ON CONFLICT (product_id, variant_name) DO NOTHING;


-- ============================================================
-- 5. AUTO-UPDATE updated_at TRIGGER
-- ============================================================

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- On products
DROP TRIGGER IF EXISTS products_set_updated_at ON public.products;
CREATE TRIGGER products_set_updated_at
  BEFORE UPDATE ON public.products
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- On product_variants
DROP TRIGGER IF EXISTS variants_set_updated_at ON public.product_variants;
CREATE TRIGGER variants_set_updated_at
  BEFORE UPDATE ON public.product_variants
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================
-- 6. STOCK MANAGEMENT RPCs
-- ============================================================

-- Safely decrement stock (floors at 0, never goes negative)
CREATE OR REPLACE FUNCTION public.decrement_variant_stock(p_variant_id bigint, p_quantity int)
RETURNS void AS $$
BEGIN
  UPDATE public.product_variants
  SET stock_quantity = GREATEST(0, stock_quantity - p_quantity),
      updated_at = now()
  WHERE id = p_variant_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Restore stock on order cancellation
CREATE OR REPLACE FUNCTION public.increment_variant_stock(p_variant_id bigint, p_quantity int)
RETURNS void AS $$
BEGIN
  UPDATE public.product_variants
  SET stock_quantity = stock_quantity + p_quantity,
      updated_at = now()
  WHERE id = p_variant_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
