-- ============================================================
-- P5 Migration: Customer Addresses
-- Multiple saved delivery addresses per user
-- ============================================================

CREATE TABLE IF NOT EXISTS public.customer_addresses (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  label           text DEFAULT 'Home',            -- 'Home' | 'Work' | 'Other'
  address_line1   text NOT NULL,
  address_line2   text,
  landmark        text,
  city            text NOT NULL DEFAULT 'Hyderabad',
  pincode         text,
  lat             float,
  lng             float,
  is_default      boolean DEFAULT false,
  created_at      timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_customer_addresses_user ON public.customer_addresses(user_id);

ALTER TABLE public.customer_addresses ENABLE ROW LEVEL SECURITY;

-- Users can only access their own addresses
DROP POLICY IF EXISTS "addresses_select_own" ON public.customer_addresses;
CREATE POLICY "addresses_select_own" ON public.customer_addresses
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "addresses_insert_own" ON public.customer_addresses;
CREATE POLICY "addresses_insert_own" ON public.customer_addresses
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "addresses_update_own" ON public.customer_addresses;
CREATE POLICY "addresses_update_own" ON public.customer_addresses
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "addresses_delete_own" ON public.customer_addresses;
CREATE POLICY "addresses_delete_own" ON public.customer_addresses
  FOR DELETE USING (auth.uid() = user_id);

-- Admins can see all addresses (for support)
DROP POLICY IF EXISTS "addresses_admin_read" ON public.customer_addresses;
CREATE POLICY "addresses_admin_read" ON public.customer_addresses
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('admin', 'rider'))
  );

-- Function: Ensure only one default address per user
CREATE OR REPLACE FUNCTION public.enforce_single_default_address()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.is_default = true THEN
    UPDATE public.customer_addresses
    SET is_default = false
    WHERE user_id = NEW.user_id AND id != NEW.id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_address_default_set ON public.customer_addresses;
CREATE TRIGGER on_address_default_set
  AFTER INSERT OR UPDATE OF is_default ON public.customer_addresses
  FOR EACH ROW
  WHEN (NEW.is_default = true)
  EXECUTE FUNCTION public.enforce_single_default_address();
