-- ============================================================
-- P7 Migration: Rider Daily Stats, Profiles & Store Defaults
-- Run this in Supabase SQL Editor
-- ============================================================

-- 1. Profiles Table Enhancement
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS must_change_password boolean DEFAULT false;

-- 2. Rider Daily Stats Table (Attendance & Online Hours tracking)
CREATE TABLE IF NOT EXISTS public.rider_daily_stats (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rider_id        uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  date            date NOT NULL DEFAULT CURRENT_DATE,
  online_minutes  int NOT NULL DEFAULT 0,
  last_updated    timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT rider_daily_stats_rider_date_key UNIQUE (rider_id, date)
);

CREATE INDEX IF NOT EXISTS idx_rider_daily_stats_date ON public.rider_daily_stats(date);
CREATE INDEX IF NOT EXISTS idx_rider_daily_stats_rider ON public.rider_daily_stats(rider_id);

ALTER TABLE public.rider_daily_stats ENABLE ROW LEVEL SECURITY;

-- Allow read access for authenticated users / admins / riders
DROP POLICY IF EXISTS "rider_daily_stats_read" ON public.rider_daily_stats;
CREATE POLICY "rider_daily_stats_read" ON public.rider_daily_stats
  FOR SELECT USING (true);

-- Allow riders to upsert their own stats
DROP POLICY IF EXISTS "rider_daily_stats_upsert_own" ON public.rider_daily_stats;
CREATE POLICY "rider_daily_stats_upsert_own" ON public.rider_daily_stats
  FOR INSERT WITH CHECK (auth.uid() = rider_id);

DROP POLICY IF EXISTS "rider_daily_stats_update_own" ON public.rider_daily_stats;
CREATE POLICY "rider_daily_stats_update_own" ON public.rider_daily_stats
  FOR UPDATE USING (auth.uid() = rider_id);

-- Enable Realtime updates on rider_daily_stats
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.rider_daily_stats;
  END IF;
EXCEPTION WHEN duplicate_object THEN
  -- Table already in publication
  NULL;
END $$;

-- 3. Ensure store_settings has row 1 seeded
INSERT INTO public.store_settings (
  id,
  lat,
  lng,
  store_name,
  store_address,
  delivery_radius_km,
  min_order_amount,
  delivery_fee_fixed,
  free_delivery_above,
  is_open,
  opening_time,
  closing_time,
  days_open,
  updated_at
) VALUES (
  1,
  17.3850,
  78.4867,
  'QuickComm Store',
  'Hyderabad, Telangana',
  5.0,
  99.0,
  20.0,
  299.0,
  true,
  '09:00',
  '23:00',
  ARRAY['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
  now()
)
ON CONFLICT (id) DO UPDATE SET
  store_name = COALESCE(public.store_settings.store_name, EXCLUDED.store_name),
  delivery_radius_km = COALESCE(public.store_settings.delivery_radius_km, EXCLUDED.delivery_radius_km),
  min_order_amount = COALESCE(public.store_settings.min_order_amount, EXCLUDED.min_order_amount),
  delivery_fee_fixed = COALESCE(public.store_settings.delivery_fee_fixed, EXCLUDED.delivery_fee_fixed),
  free_delivery_above = COALESCE(public.store_settings.free_delivery_above, EXCLUDED.free_delivery_above),
  is_open = COALESCE(public.store_settings.is_open, EXCLUDED.is_open);

-- 4. Storage Buckets (for Product, Category, and Brand Images)
INSERT INTO storage.buckets (id, name, public)
VALUES 
  ('product-images', 'product-images', true),
  ('category-images', 'category-images', true),
  ('brand-logos', 'brand-logos', true)
ON CONFLICT (id) DO NOTHING;

-- Storage policies: public view, admin upload/delete
DROP POLICY IF EXISTS "Public view store images" ON storage.objects;
CREATE POLICY "Public view store images" ON storage.objects
  FOR SELECT USING (bucket_id IN ('product-images', 'category-images', 'brand-logos'));

DROP POLICY IF EXISTS "Admin upload store images" ON storage.objects;
CREATE POLICY "Admin upload store images" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id IN ('product-images', 'category-images', 'brand-logos')
  );

DROP POLICY IF EXISTS "Admin delete store images" ON storage.objects;
CREATE POLICY "Admin delete store images" ON storage.objects
  FOR DELETE USING (
    bucket_id IN ('product-images', 'category-images', 'brand-logos')
  );

